services:
  ref:
    build: ./ref
    logging:
      options:
        max-size: "5m"
        max-file: "1"
    networks:
      - p1-net
      - p2-net
      - to-api
    extra_hosts:
    - "host.docker.internal:host-gateway"
  p1:
    build: ./p1
    logging:
       options:
        max-size: "3m"
        max-file: "1"
    networks:
      - p1-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  p2:
    build: ./p2
    logging:
      options:
        max-file: "1"
         max-size: "3m"
    networks:
      - p2-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  p1-net:
    internal: true
  p2-net:
    internal: true
  to-api:
    internal: false
