services:
  ref:
    build: ./ref
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "1"
    networks:
      - p1-net
      - p2-net
  p1:
    build: ./p1
    logging:
      driver: json-file
      options:
        max-size: "3m"
        max-file: "1"
    networks:
      - p1-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
  p2:
    build: ./p2
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: "3m"
    networks:
      - p2-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M

networks:
  p1-net:
    internal: true
  p2-net:
    internal: true
